dynet_seed: 42
dynet_mem: 2048
dynet_gpu: False
dynet_autobatch: 1
verbose: True
model_type: 'Stacked_BILSTM'
hidden_dim: [64,64]
embed_dim: 300
classifier: 'linear'
classifier_input_dim: 512
classifier_hidden_dim: 300
output_dir: 'output'
vocab_file: 'snli_vocab_file'
laplace_smoothing: 0.0
min_freq: 0
vocab_size: 1000000
model_file: 'snli_stacked_test_model'
pretrained_wembs: 'snli_glove_300.npy'
classifier_layer_norm: False
train:
  train: True
  train_file: 'snli/tiny_train.txt'
  dev_file: 'snli/dev.txt'
  num_iters: 20
  batch_size: 32
  trainer: 'adam'
  learning_rate: 0.001
  gradient_clip: -1.0
  learning_rate_decay: 0.5
  patience: 0
  dropout: 0.1
  label_smoothing: 0.0
  l2_reg: 0.0
test:
  test: True
  test_file: 'snli/test.txt'
